### ISSUE TITLE
development framework with Docker

### ISSUE THREAD

**Issue by gfarm-admin** [oss-tsukuba/gfarm#1067]
examples:
$ cp -r gfarm2fs gfarm/
$ cd gfarm/docker/dev
$ editor config.mk  # set GFDOCKER_IP_VERSION, GFDOCKER_SUBNET, and GFDOCKER_START_HOST_ADDR
$ cd dist/centos7/src  # use CentOS 7
$ make help  # display usage.
$ make reborn  # up the containers.
$ make shell  # enter the container.
$ make regress  # execute regress.
$ make down  # down the containers.

Reported by: soum-itoshimo

Original Ticket: [gfarm/tickets/1067](https://sourceforge.net/p/gfarm/tickets/1067)

**Comment by takuya-isbs** [comment]
commit de432ac19e1febede319d69b8cb26260b5519851
