### ISSUE TITLE
gfarm.effective_perm xattr (extended attribute)

### ISSUE THREAD

**Issue by takuya-isbs** [oss-tsukuba/gfarm#1105]
gfarm.effective_perm is a virtual extended attribute.
The returned value means flags like R_OK, W_OK and X_OK of access(2).
0x04 -> R_OK
0x02 -> W_OK
0x01 -> X_OK
The flags of a file vary from user to user.

Example of use:
  - gfarm_xattr_caching_pattern_add(GFARM_EA_EFFECTIVE_PERM);
    gfs_getxattr_cached(path, GFARM_EA_EFFECTIVE_PERM, &v, &size);  /* char v; size_t size=1; */
  - gfxattr -g GFARM_URL gfarm.effective_perm | od -An -tx1
  - gfls -e GFARM_URL | awk '{print $1}'

**Comment by n-soda** [comment]
this was already released as part of gfarm-2.7.18
