### ISSUE TITLE
gfmd may crash when a parent directory has default ACL

### ISSUE THREAD

**Issue by takuya-isbs** [oss-tsukuba/gfarm#1108]
`<err> [1003180] db_journal_store_thread : seqnum=608 ope=INODE_CTIME_MODIFY : no such object`

gfjournal -lv /var/gfarm-metadata/journal/0000000000.gmj

         606 BEGIN                       24      30125
         607 INODE_MTIME_MODIFY          44      30149 ino=18;time=20201018-201937.568648GMT
         608 INODE_CTIME_MODIFY          44      30193 ino=20;time=20201018-201937.568703GMT
         609 INODE_MODE_MODIFY           36      30237 ino=20;uint32=16832
         610 INODE_ADD                  117      30273 ino=20;gen=0;mode=16832;nlink=2;size=0;user=user1;group=gfarmadm;atime=20201018-201937.568648GMT;ctime=20201018-201937.568703GMT;mtime=20201018-201937.568648GMT
         611 XATTR_ADD                   80      30390 ino=20;xml_mode=0;attrname=gfarm.acl_default;size=19;value="..................."
         612 XATTR_ADD                   64      30470 ino=20;xml_mode=0;attrname=gfarm.acl_access;size=4;value="...."
         613 DIRENTRY_ADD                45      30534 ino=20;entry_ino=20;entry_name=.;entry_len=1
         614 DIRENTRY_ADD                46      30579 ino=20;entry_ino=18;entry_name=..;entry_len=2
         615 INODE_NLINK_MODIFY          40      30625 ino=18;uint64=4
         616 DIRENTRY_ADD                47      30665 ino=18;entry_ino=20;entry_name=qj6;entry_len=3
         617 END                         24      30712

**Comment by n-soda** [comment]
already released as gfarm-2.7.18
