### ISSUE TITLE
Can't access _gfarmfs user to create secret key 

### ISSUE THREAD

**Issue by WGandy** [oss-tsukuba/gfarm#1131]
This is the next issue I encountered (previous issue - https://github.com/oss-tsukuba/gfarm/issues/1130). 

When trying to add the user, I find that the user already exists. 
`$ sudo useradd -c "Gfarm gfsd" -m _gfarmfs`
`useradd: user '_gfarmfs' already exists`

And of course, I can't access the user because I don't know it's password. 
`$ su gfarmfs`
`Password: `
`su: Authentication failure`

Does this user have a password that was created during previous installation steps? I assume that I can't change the password as that will disallow access by the daemon?  

EDIT: This may be jumping ahead because I am still having an issue with this command. 
```
# config-gfarm -A <myuser>
WARNING: command not found: pg_ctl
WARNING: command not found: psql
config-gfarm: aborted
config-gfarm failure
```

**Comment by otatebe** [comment]
To execute config-gfarm, you need additional packages; postgresql and postgresql-client.
`# apt-get install postgresql postgresql-client`

To change the _gfarmfs user, try
`# sudo su - _gfarmfs`

Hope this helps.

**Comment by WGandy** [comment]
postgresql and postgresql-client-12 are both dependencies that were installed when gfmd was installed. 
```
The following additional packages will be installed:
  gfarm-client gfarm2fs libgfarm1 libllvm10 libpq5 postgresql postgresql-12 postgresql-client-12 postgresql-client-common postgresql-common sysstat
```
I also tried installing 'postgresql-client' separately and a few extra items were installed. But I still get the same error that psql and pg_ctl can't be found. 

I DO see psql in my regular user's /usr/bin and I can run it as my user (but I get an error telling that my user does not exist - presumably because my user does not exist in the postgres database so that makes sense). Conversely, I don't see pg_ctl in the /usr/bin directory. From my research it seems that pg_ctlcluster is the more correct executable to run in place of pg_ctl and pg_ctlcluster is indeed in path as well. It seems to me that these 'not found' errors are happening because they are not in path for a different user that the config-gfarm is using? I've found that psql **is** in path for the root user.  

Lastly, I played around with deleting the _gfarmfs user and then running 
`useradd -c "Gfarm gfsd" -m _gfarmfs`. This does indeed allow me to 
`sudo su _gfarmfs` without a password but.... 

I get this error:
`$ gfkey -f -p 31536000
gfkey: cannot open gfarm2.conf`

Again, it seems like something is running as the wrong user??

**Comment by WGandy** [comment]
Also, I'm trying this install on both an x86 machine running linux Mint 20.3 AND a Raspberry Pi 4B running 64bit Raspberry Pi OS. I'm running into the same issues on both platforms.

**Comment by otatebe** [comment]
Would you paste the output of `sh -x config-gfarm -A <username>`?

`psql` and `pg_ctl` should be found in a directory of the output of `pg_config --bindir`
But it seems to fail for some reason.

Or, if it is `/usr/lib/postgresql/12/bin`,  you can explicitly specify by -P as follows
`config-gfarm -A <username> -P /usr/lib/postgresql/12`

`config-gfarm` creates the gfarm2.conf file.  It is necessary to execute `gfkey`.

**Comment by WGandy** [comment]
`$ sudo sh -x config-gfarm -A <username>`
`sh: 0: Can't open config-gfarm`

Aha! Postgresql Prefix! Your second option worked.
`config-gfarm -A <username> -P /usr/lib/postgresql/12`

It makes full sense that gfkey requires a conf file. Thank you for clarifying. 

The gfkey line ran without issue although I did have to run it as you suggested: 
`sudo su - _gfarmfs`

Will there be an issue that I created a different password for the user _gfarmfs OR did the config-gfarm undo that anyway?

**Comment by otatebe** [comment]
It does not matter _gfarmfs has a password or not.  We recommend not to have the password because it is a system account.

The last issue is probably that config-gfarm fails to find a directory for pgsql and pg_ctl.
Do you have pg_config?  Can you execute pg_config?

**Comment by WGandy** [comment]
config-gfarm appears to be running correctly with the /usr/lib/postgresql/12 directory hint. 

My current snag is that 
```
gfhost -l
-.--/-.--/-.-- - X86_64-linuxMint20.3-linux 4...
```

I understand that the dashes indicate that the host is up, but gfsd on the host cannot be accessed. 
Any suggestions for this?

**Comment by WGandy** [comment]
Also, are there any permission or ownership requirements for the spool directory?

**Comment by otatebe** [comment]
OK.  it seems this ticket can be closed.
For your next question, -.--/-.--/-.-- means the gfsd is not executed.
To configure gfsd, you need to execute config-gfsd.
For details, refer to SETUP.en document.
