### ISSUE TITLE
gfhost fails with segmentation fault

### ISSUE THREAD

**Issue by Harvey-13** [oss-tsukuba/gfarm#1158]
Running gfhost on metadata server may fail with segmentation fault when the server has some sort of tun networks, the details can be referred to [here](https://stackoverflow.com/questions/22767155/when-will-ifa-addr-be-null-on-calling-getifaddrs). So in the source file [host.c](https://github.com/oss-tsukuba/gfarm/blob/2.8/lib/libgfarm/gfarm/host.c), line 448, ifa->ifa_addr may be a null pointer, which leads to segmentation fault like below.
```sh
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7f0ec4c in gfarm_get_ip_addresses (
    countp=countp@entry=0x7fffffffe424,
    ip_addressesp=ip_addressesp@entry=0x7fffffffe428)
    at ./host.c:448
warning: Source file is more recent than executable.
448                     if (ifa->ifa_addr->sa_family == AF_INET &&
(gdb) l
443                     save_errno = errno;
444                     gflog_notice_errno(GFARM_MSG_1004305, "getifaddrs");
445                     return (gfarm_errno_to_error(save_errno));
446             }
447             for (n = 0, ifa = ifa_head; ifa != NULL; ifa = ifa->ifa_next) {
448                     if (ifa->ifa_addr->sa_family == AF_INET &&
449                         (ifa->ifa_flags & IFF_UP) != 0) {
450                             n++;
451                     }
452             }
(gdb) p ifa->ifa_addr
$1 = (struct sockaddr *) 0x0
(gdb) p ifa->ifa_name
$2 = 0x55555558fdb4 "tun0"
```

**Comment by n-soda** [comment]
I think this problem was fixed in
commit 5b46aa9e43d1a2728c980197cc61a99b5d0f5a86 (2.7 branch)
and
commit 7dccb42da08c2a6f9d05c4f87362eb9f311d5e9a (2.8 branch).

and these will be released as gfarm-2.7.26 and gfarm-2.8.1.

If the problem remains, please let me know.
Thanks!
