### ISSUE TITLE
FTBFS on GNU Hurd

### ISSUE THREAD

**Issue by gfarm-admin** [oss-tsukuba/gfarm#805]
GNU Hurd needs to define MAXHOSTNAMELEN, MAXPATHLEN and PATH_MAX, see attached patch.

Reported by: ownerless at SourceForge

Original Ticket: [gfarm/tickets/805](https://sourceforge.net/p/gfarm/tickets/805)

**Comment by n-soda** [comment]
the GNU Hurd patch was applied as part of commit 732b7caa92c17597ece7e685f1955571da784ffc
and released as gfarm-2.7.17

this patch was supplied by @onlyjob, thanks!
